Rull_List = []

TERMINALS = []
NON_TERMINALS = []

GRAMMER = {
    1: "Goal Source EOF",
    2: "Source ClassDeclarations MainClass",
    3: "MainClass public class Identifier { public static void main () { VarDeclarations Statements }}",
    4: "ClassDeclarations ClassDeclaration ClassDeclarations",
    5: "ClassDeclarations",
    6: "ClassDeclaration class Identifier Extension { FieldDeclarations MethodDeclarations }",
    7: "Extension extends Identifier",
    8: "Extension",
    9: "FieldDeclarations FieldDeclaration FieldDeclarations",
    10: "FieldDeclarations",
    11: "FieldDeclaration static Type Identifier ;",
    12: "VarDeclarations VarDeclaration VarDeclarations",
    13: "VarDeclarations",
    14: "VarDeclaration Type Identifier ;",
    15: "MethodDeclarations MethodDeclaration MethodDeclarations",
    16: "MethodDeclarations",
    17: "MethodDeclaration public static Type Identifier ( Parameters ) { VarDeclarations Statements return GenExpression ; }",
    18: "Parameters Type Identifier Parameter",
    19: "Parameters",
    20: "Parameter , Type Identifier Parameter",
    21: "Parameter",
    22: "Type boolean",
    23: "Type int",
    24: "Statements A",
    25: "A Statement A",
    26: "A",
    27: "Statement { Statements }",
    28: "Statement if ( GenExpression ) Statement else Statement",
    29: "Statement while ( GenExpression ) Statement",
    30: "Statement for (Identifier = Integer ; RelTerm ; Identifier += Integer ) Statement",
    31: "Statement Identifier = GenExpression ;",
    32: "Statement System.out.println (GenExpression ) ;",
    33: "GenExpression Expression G",
    34: "G E F",
    35: "Expression BB",
    36: "BB B BB",
    37: "BB",
    38: "B + Term",
    39: "B - Term",
    40: "Term Factor C",
    41: "C * Factor",
    42: "C",
    43: "Factor ( Expression )",
    44: "Factor Identifier D",
    45: "Factor true",
    46: "Factor false",
    47: "Factor Integer",
    48: "D",
    49: "D .Identifier DD",
    50: "DD",
    51: "DD ( Arguments )",
    52: "RelExpression RelTerm E",
    53: "E",
    54: "E && RelTerm E",
    55: "RelTerm Expression F",
    56: "F == Expression",
    57: "F < Expression",
    58: "Arguments GenExpression Argument",
    59: "Arguments",
    60: "Argument , GenExpression Argument",
    61: "Argument",
    62: "Identifier identifier",
    63: "Integer integer",
    64: "G"
}

PARSER_TABEL = {
    "Goal": {"class": 1, "public": 1},
    "Source": {"class": 2, "public": 2},
    "MainClass": {"public": 3},
    "ClassDeclarations": {"public": 5, "class": 4},
    "ClassDeclaration": {"class": 6},
    "Extension": {"extends": 7, "{": 8},
    "FieldDeclarations": {"public": 10, "}": 10, "static": 9},
    "FieldDeclaration": {"static": 11},
    "VarDeclarations": {"{": 13, "if": 13, "while": 13, "for": 13, "identifier": 13, "System.out.println": 13, "boolean": 12, "int": 12},
    "VarDeclaration": {"boolean": 14, "int": 14},
    "MethodDeclarations": {"}": 16, "public": 15},
    "MethodDeclaration": {"public": 17},
    "Parameters": {"boolean": 18, "int": 18, ")": 19},
    "Parameter": {",": 20, ")": 21},
    "Type": {"boolean": 22, "int": 23},
    "Statements": {"{": 24, "if": 24, "while": 24, "for": 24, "identifier": 24, "System.out.println": 24, "}": 24, "return": 24},
    "Statement": {"{": 27, "if": 28, "while": 29, "for": 30, "identifier": 31, "System.out.println": 32},
    "GenExpression": {"+": 33, "-": 33, " ": 33, "&&": 33, ")": 33, ";": 33, ",": 33},
    "Expression": {"+": 53, "-": 53, "&&": 53, ")": 53, ";": 53, ",": 53, "=": 53, "<": 53},
    "Term": {"(": 40, "true": 40, "false": 40, "identifier": 40, "integer": 40},
    "Factor": {"(": 43, "true": 45, "false": 46, "identifier": 44, "integer": 47},
    "RelExpression": {"+": 52, "-": 52, "=": 52, "<": 52},
    "RelTerm": {"+": 55, "-": 55, "=": 55, "<": 55},
    "Arguments": {"&&": 58, "+": 58, "-": 58, ",": 58, ")": 59},
    "Argument": {",": 60, ")": 61},
    "Identifier": {"identifier": 62},
    "Integer": {"integer": 63},
    "A": {"{": 25, "if": 25, "while": 25, "for": 25, "identifier": 25, "System.out.println": 25, "}": 26},
    "B": {"+": 38, "-": 39},
    "BB": {"+": 36, "-": 36, "&&": 37, "=": 37, "<": 37, ")": 37, ";": 37, ",": 37},
    "C": {"*": 41, " ": 42},
    "D": {" ": 48, ".": 49},
    "DD": {" ": 50, "(": 51},
    "E": {" ": 53, "&&": 54},
    "F": {"=": 56, "<": 57},
    "G": {}
}